#!/bin/bash
# Points the Homebrew tap at a release that already exists.
#
# The formula is three facts — a version, a checksum and a URL — and all three
# come from the release that was just published, which is why this runs after
# it. A tap updated first advertises a download that is not there yet.
#
# Usage: scripts/update-tap.sh <version> [sha256]
#        scripts/update-tap.sh --print <version> [sha256]
#
# `--print` writes the formula to stdout and touches nothing. The checksum is
# read from dist/mat-<version>.tar.gz.sha256 when it is not given.
set -euo pipefail

cd "$(dirname "$0")/.."

PRINT=""
if [ "${1:-}" = "--print" ]; then PRINT=1; shift; fi

VERSION="${1:-}"
[ -n "$VERSION" ] || { echo "usage: update-tap.sh <version> [sha256]"; exit 2; }
VERSION="${VERSION#v}"
SHA="${2:-}"

REPO="${MAT_REPO:-philipparndt/mat}"
TAP="${MAT_TAP:-philipparndt/homebrew-mat}"
ARCHIVE="dist/mat-$VERSION.tar.gz"

if [ -z "$SHA" ]; then
	test -f "$ARCHIVE.sha256" || { echo "no $ARCHIVE.sha256 and no checksum given"; exit 1; }
	SHA=$(awk '{print $1}' < "$ARCHIVE.sha256")
fi
[[ "$SHA" =~ ^[0-9a-f]{64}$ ]] || { echo "not a sha256: $SHA"; exit 1; }

[ -n "$PRINT" ] || command -v gh >/dev/null \
	|| { echo "gh is not installed — brew install gh"; exit 1; }

# The tap, in a temporary clone: it is another repository, and a checkout of it
# kept around is how it comes to be edited by hand and overwritten by this.
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
FORMULA="$WORK/mat.rb"

# A formula rather than a cask: mat is a command, and a formula links it into
# the PATH and is not quarantined. The binaries are the signed, notarised ones
# from the release, not built again on the user's machine — a Rust and a Swift
# toolchain to install a CLI is a lot to ask, and a rebuild would not be the
# notarised build.
#
# The archive is universal, so there is one url for both processors.
# `share/mat` is where mat looks for the sample library when it is installed
# (crates/mat-core/src/arrange.rs, `sample_library`).
cat > "$FORMULA" <<RUBY
# typed: strict
# frozen_string_literal: true

# mat renders .song files — music written as text — to audio. Generated by
# scripts/update-tap.sh in the mat repository on every release.
class Mat < Formula
  desc "Music as text: render .song files to audio"
  homepage "https://github.com/$REPO"
  url "https://github.com/$REPO/releases/download/v$VERSION/mat-$VERSION.tar.gz"
  sha256 "$SHA"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  depends_on :macos

  def install
    bin.install "bin/mat", "bin/mat-au"
    share.install "share/mat"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mat --version")
    (testpath/"test.song").write <<~SONG
      tempo 120
      instrument kit samples
        kick "samples:sonic-pi/bd_haus.wav"
      pattern beat grid=1/4
        kick x...
      track drums
        instrument kit
        play beat
    SONG
    output = shell_output("#{bin}/mat render #{testpath}/test.song -o #{testpath}/test.wav 2>&1")
    refute_match "warning", output
    assert_path_exists testpath/"test.wav"
  end
end
RUBY

if command -v brew >/dev/null; then
	echo "==> brew style" >&2
	brew style "$FORMULA" >&2 || echo "    (style complained — look, but not fatal)" >&2
fi

if [ -n "$PRINT" ]; then
	cat "$FORMULA"
	exit 0
fi

# The release has to be there, and has to be the one this formula pins: the
# digest is what GitHub computed for the asset it is serving, so this compares
# the formula against the download rather than against whatever is in dist/.
PUBLISHED=$(gh release view "v$VERSION" --repo "$REPO" --json assets \
	--jq ".assets[] | select(.name == \"mat-$VERSION.tar.gz\") | .digest // \"\"" 2>/dev/null || true)
if [ -z "$PUBLISHED" ]; then
	echo "no mat-$VERSION.tar.gz published at v$VERSION in $REPO" >&2
	echo "publish the release first — a formula pointing at a download GitHub does" >&2
	echo "not have is a failed 'brew install' for whoever is quickest" >&2
	exit 1
fi
if [ "$PUBLISHED" != "null" ] && [ "$PUBLISHED" != "sha256:$SHA" ]; then
	echo "the published archive is not the one this formula pins:" >&2
	echo "  formula:   sha256:$SHA" >&2
	echo "  published: $PUBLISHED" >&2
	exit 1
fi
echo "==> v$VERSION is published and the archive matches"

echo "==> Cloning $TAP"
gh repo clone "$TAP" "$WORK/tap" -- --quiet
mkdir -p "$WORK/tap/Formula"
cp "$FORMULA" "$WORK/tap/Formula/mat.rb"

cd "$WORK/tap"
SHORT_TAP="${TAP/\/homebrew-//}"
# A tap without a README is a repository nobody can tell the purpose of; the
# first release writes one, and a README somebody has edited since is theirs.
if [ ! -f README.md ]; then
	cat > README.md <<README
# $SHORT_TAP

Homebrew tap for [mat](https://github.com/$REPO), music as text.

    brew tap $SHORT_TAP
    brew trust $SHORT_TAP
    brew install mat

Written by \`scripts/update-tap.sh\` in the mat repository on every release —
edit that, not \`Formula/mat.rb\`.
README
	git add README.md
fi
# `status`, not `diff`: in a tap that has never had a formula the file is
# untracked, and `git diff` would say nothing changed.
if [ -z "$(git status --porcelain)" ]; then
	echo "==> $TAP already points at $VERSION"
	exit 0
fi
git add Formula/mat.rb
git commit -q -m "mat $VERSION"
# An empty tap has no branch yet; this one becomes main.
git branch -M main
git push -q origin main
echo "==> $TAP now installs mat $VERSION"
echo "    brew tap $SHORT_TAP && brew trust $SHORT_TAP"
echo "    brew install mat"
